version: 2
jobs:
  build:
    docker:
      
      # specify the version you desire here
      - image: circleci/node:8.9.0       
      - image: circleci/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
      - ./mounts/mysql:/var/lib/mysql
      - ./mounts/scripts:/scripts
    ports:
      - "3307:3306"
    depends_on:
      - circleci/node
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: mysql -h 127.0.0.1 -u root -e "create database test"

      - save_cache:
          paths:
            - node_modules
            - ../server:/node/server
             - mounts/scripts/createUser.sh:/node/createUser.sh:ro
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
      